{{- if .Values.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "sa-service.fullname" . }}
  labels:
    {{- include "sa-service.labels" . | nindent 4 }}
spec:
  minAvailable: {{ default 1 .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "sa-service.selectorLabels" . | nindent 6 }}
{{- end }}

