{{- if .Values.sealedSecretExample.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: example-only-replace-with-generated-secrets
spec:
  encryptedData:
    EXAMPLE: {{ required "sealedSecretExample.encryptedValue es obligatorio cuando enabled=true" .Values.sealedSecretExample.encryptedValue | quote }}
  template:
    metadata:
      name: example-only-replace-with-generated-secrets
    type: Opaque
{{- end }}

