# Generado con kubeseal. No contiene secretos en texto plano.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sa-platform-product-db-secret
  namespace: sa-p8
spec:
  encryptedData:
    DATABASE_URL: AgCM/AA8SCtFZHAIG3DRAxBtuf74NEwinLAU2bC+/A3WVFAzEv3tmVXeaSYMaNxVNoGhAS6o8Y8DOJRnoog8gpb3xtVVhEEqzRQgkUhMTye75K0u8ikgthvkHyQDHC++2jgueN2Zfmgv6xFJZUqISUEq9FYsFxqL7XpY2zo6Nq0WypNU15CoG9JBFCpw1/5GkEv/OODly+ATCpnBQ65d2E2Uh4gtDpZcJ5RhYMymGEDYIvgxhAlZUAIkFQnMBhCoUW7VGJ/s2x9kuSH3On9KO9uN1bgx8YprRmcwS9Jpt6CVDPI6HW/kFpWPeekMsRUHebTRZalmJQdx0oE6eqg4ojdrVz/0J8Y6T7Z83CuNq9Q2UudoArrzLyiPyY94lF1Xob+zhecru1m5UitQbhCn7cGrQpjS5pGGaVeZiHdNDKFtNPgsJHvoJCqqo57i/aXyhkDHdqKSXySnb92vkT0Zv4bFiVrE0sQZLyPX9ooE5mRzkSI90eFfYdHaPWFj0T62vD16zl4XQQbfR8nFwT0v4kZ6xzMu3iTXGXS4m2+NRZwBUk/NfNTWlHnZTBS+JEAaVi2a1q5PKMjjhbdYHpWyFbvcZqG83bS8Uzz07gM6qXRKL5DL+rFvZYhnGpG6n/j3TJhKiyI4F1JfgreBucE0NAh4YLPjU30zVBratbF5wv3zRcAyG+dAMbwr/+tId5+Z+py1Mba+V/AzS8o9kmPsLU99Zre/E4DfyowB0aLUN28lBu3pLuXxnbXm+QbuiRYB475cwDcFXMVLQU5p+W1vGwONs0iL13trMPYWVY3/zYNmBN2M8kv6TAOR8+7PB5wURRPYeEj4sSM=
  template:
    metadata:
      name: sa-platform-product-db-secret
      namespace: sa-p8
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sa-platform-order-db-secret
  namespace: sa-p8
spec:
  encryptedData:
    DATABASE_URL: AgArdy5QJr1hRug0rLCK7LWwg6r3vHSTiANJCH4k8hzBLi11bi9emW/D+CuNOEDqmyFGVOabIDCkY9PbUsY02pEQG8g4ObgiZ9KqEfkhwYXrFBZIwskRxazzAwLHE8lc0UedMXZniJ9A5WqlnSVCAOd6BcvzxUSZSs5Tu0ijD1jiw0VFwajJ3laTWLnB2sWc1ne7/HaHPA7VdgzjfKS6i/EwhT7JdUJkxAAEvLp933gnZef76SB7+bjC/fP2hPV2O9fQzrdw8/QNtfBTUuF05RSMAu8dfgolNcgLfehUUXvVdkLA4WBb53yxp8RzGV1TVcbty/tfnj6tKp0IiUBfI/J4sKDJ14Nc1Qx7hLpzDXk/5b3j2U9H4XKmpS2x1rV7Yqcsjum6AmWBgxuqnbRx3KnuJz4WH4LbsGTUW44LDPVS5DJUfaBQbBbtBcyrgRzuI7On3V4jM3EK9DBWrWeECmy2R9t2EZdqguVHAULAmMmR6d/mm3aZYSuB4z844wSBLEpCzX8VO33JJgiHBQwLHXeK9GxxzlNSo3qUzZXhTxKPVXtncpq8nJOg8kXKm4qVGmOecEvHCb5w26aOdLlrfc72lvtPDhz36O5xVPIO/2Ofmo0frS9xj8VmAN1PDJpfgTUAOHzoLtBS/7VcaJoOOjbOUjwQrIDUc7QoQArrka9QabzuKz4Rzk4iyyD7+S+SPOEuWTbx6wqm3H/sySWgu4tGSAVFh4D7gr2B4Xd/ubm36xUmGWR32Ku6Qe9yNh9AlBYYUeLz/CaiPy4qHyvhJGLenlKLvaQwr8jcabtkpIl0zpZ9zIye5+H2/k9SZ1GGILQUY0mb
  template:
    metadata:
      name: sa-platform-order-db-secret
      namespace: sa-p8
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sa-platform-customer-db-secret
  namespace: sa-p8
spec:
  encryptedData:
    DATABASE_URL: AgAj3naaY+EJn17Ii5IYSuWq4GGLPK3BKJtpjAyQ00qf0uSRaGYIFn34vp5ud8T0KLmvAnFBHbvBWDs7OpakpPIcgYKcvLkOigydWJWTxhVmOGebl3Yvei3miZzCM2eASkYHIcvYFm///g3PSI1u40D0egpOhqlkjeIxV2oW8r81TYWdVv3ASglv2bzg2qUk1qHZfOkuLAVKyia8RvZyhol+QgnEet9bNnzBmzExavuhT72kHnjZUQI7cHDNETC0IuTMc/2M1Foew7XgC2a91QSULv4xUEvd5/fhMrKortKXSn38Q3IbTtrga87Mt9tOjjNC/c9/I7mmiSGhJhpn3H9FL9pdIHjl/zof8Zcrvl6Sx+mIac1B3BVGXKDYseDgHxydQIOqahN1n3fjngod0pdopiDkdU4R+h8U4cJH32kjIpFfb2YcliSb3WRhZN9EHi7p1k8M4zBBrENr1ty0GOG1aAoQFhRpTjUELvSWg6vCNJT/iR/TtZaf5NpySUe3wfq3yJC2dOwgHi9m4xvBaJJiGeqkkVkcfufJXxzb7K+7VprdJkDgBP2+eIzJ+9inzbvOGx7jJ6ys/Oj4OAYj/+GlteAwFThHTx56B1DcdVoT6Ir9u082eZie/YsnsmZ4Cel+ubfcoZFrtr5VdV1X/F93UnMSIjZwo1bkKBypECIOOQktpy+3dCW477zGRgzeBeveLP2yK4DD73R4V6XT3YjgQ8QCMPwgNX+FcUw2vQFwasZYxVps8+KXJAorPPnQVFBfgnq6deNweSI5MJ7nj51RE7bkOjpnojYu7Mv4KihQ7G6SSCS5ie66Pd8tGRji9oCvm8Yom5mJ
  template:
    metadata:
      name: sa-platform-customer-db-secret
      namespace: sa-p8
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sa-platform-payment-db-secret
  namespace: sa-p8
spec:
  encryptedData:
    DATABASE_URL: AgA1BLIiKSVlYBwZnbTMM4n+JELZZ6qg1e4l9iJnt8qTLmAPh9tnAj1h0XqrD25+sQv6ZrLvpQCh8DkfR3CEgF44iAlDtxquT2Pr/uXucerJHcbwJX/HJghteCwqPycE6ExWNC4zfo0aayVGDR9OlLVgXJgSRgosQYSU4o7CoiMsADVoo7u3Usf92Z0fRyAc3eX/Pa++DwANAE4Dybl3OPXoSPkz8bRiR0qkKtSQVk7N5wHoTXCTp5oFaNkDeBI44wsFeKAkJDdPam5MMtFd/pKbFMDG50tAIT1WFmvY1vldWFZD4nzCxTKIuXmTq1GF1LE/thL3cbwHNdBr1H2JIbeCAhKR9XleeJUmOUB+Z4asd6fhQfO+EzORL/YKY3RqwlLpqSvBYpGO7Gsnw5wu7Ht6pFhQcDsKBKULT/KluLVnjD8DAkqvFzWX2BmvM2+KuzzvHQHmzNlYSYAyMYqgbTmOiNKYc3kRrb9kG4JWuv9qn9GOv9Ghf6ESdahiQFLk0n9ATGwukCaHhsU1qZsJwaV5altz7TR+yvkhfgBbSipHw76nSsSfT2iLz6ontcnXF2WN+nJxVLABCeCKBdybZaOCbwz8WQjtLyiHsB+cHLIRGcnqxQBJFDlVZaN9dQ0gF3MxBoX4KVsoKCfPAlMD6glpyMO+5xskGXQIHtXeAH+KYyRWU+K3W0Jv1ORp/EDocfbUTrXQ/XXoBNn/KlPr6yFhhKq9ujRzGO3kc8tHB1lfuZzEds/Nrh8dbd4kGstNhP138s+/aCiUufV65Klp1WcLebIUzYqXuXM4+7q6AxIPY3DWBBUVXB6GuJRV4n4COnizAkhyfCc=
  template:
    metadata:
      name: sa-platform-payment-db-secret
      namespace: sa-p8
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sa-platform-authentication-db-secret
  namespace: sa-p8
spec:
  encryptedData:
    DATABASE_URL: AgBFlu9zVnCuFLJWY5gkKLc+LiVTV9Y7JbE1lSOz5QLLJXNogJ9fNKLhJHbOSNdlcS9QtwJZ3rTvHCN83lxHeykev5qnFSrA7srM4YI05ccXb2vt7DrsHcLfoU6MhZhmEhJ4o10E0nvX8trsgFspCBlsjJhUm8DPFWPjjozy/lJaBO4my7cxzVCb2FYCgPTy2rvMpgoBkSadCgWqW0srUNv8S3TXW6iZUiYu0zhXMQ91uhx7rTZKAuIQDZmV+Rak9HBVt1CPleKRpR9KQ3IsATXFVfORpUSaND/kRFYcTwVT4TIjnUx4ryCSXL309DmLSb8W7iafuDfm38/hqoWEqPssP6x8VQTYAzrIxbcDo/dJJld/ur567I1GyC/Y2fM0WJuEGL6bppJXBjRDsLlWlLCM23oAdVF8zoVoL3Zm2irbL1QuI2wlcIeFIazLJHpXi5gPn5q6RZrBHY2mKnTUl2BWCuSvsXgEPszz6gFFSFlfm4gN9/oMmE+2tQEwKQrdCmqgjhnzQP/ixwzJcaH4SKbrARUPcPtMt3wweIB/hFIHvGb0I/ZRyMTIk1jb0sUmCbpdXQl2p4+MuxE4CyiAUG8TqHmyhKV3hQAjsDL2zwVFlL5Z/+Z0+Z3/CfJvYPJIFu5ymsZxm7HNXXffcjuaJDVga7y5D23SpDHHs4v+9rumyRJV0hIJkVXNHRGxxHMllfrIt3wfHnasmH+bt4BO3ey8HsxgnWsNsA3Wi8OS09ud4Q3jC81Jfhdci2BTT75Jh0hwy/461AGH1BmVTYg27B/MDMkH4AK99uXet6zADJ5O7NzBlB5keJmNAFFZP757ZHk29SV+TEFpSKq2KBo=
  template:
    metadata:
      name: sa-platform-authentication-db-secret
      namespace: sa-p8
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sa-platform-authorization-db-secret
  namespace: sa-p8
spec:
  encryptedData:
    DATABASE_URL: AgCLq1BCigEiaxl7UUIDziFzn04cH5Gz4y6MbcEt7gLiDxDTPJom5FpEXLTbQzqKRXpohVHyVVq9qPPvUHZiRq5FftUqLJVKIIF11P1kL6HVcJXjaQdOL22MynltKRjGLjSdKOVe+eMzDSdHgkBZW+kt0YLbQq7bc8hM51MbRKMEsHTtLvRtBm6Cw4FPUjnxzmPkMdpJSNAOQWmYeZgDgGdCv2rbes3luWBZSmsh40U4e6wXclT5rvO1zMM8CY+BxP27m4avSbiG5ecRwwZ/MeQp8Y6NZ2+XupacyMSHu1JfAhmE+yatN6DqVQp5Q7GRD5jqYp5zgKS87Ybeub/DWWquRm8zSCqUKCpO4ToJvDogbBHzZzV1sJdYm2w53yOeUxXTjpHRboO5LZF5ABvjlPyOIqwxHo1pgbbYD4Wh6HGJmZlb0IIkANSxGr8cfUIYmuGioSxGQXv1yCcR25pjyC4UIc9t7qNE3hYFLrNwIxZ0xwmet8B0PaEBTkT2s29dv8e0o140JiKTDrTYLlht4708Y8RnCeVAsMAY+78We2kBcTFbu2ZMU9Hx9a41fdCxvs3YD5JAcLvwNoRC3RCcui1VhkC3c4TKBJF3X1vBrzMDGEyZkTR9oFYKJG64OHKCfrl7ghMcaARUfwWaSxNzfKpnXdt7Ul2fXwpyjbVoCviLypxTM1aHbEwREOhiSNRLqTyGQ6yqN46JJrscfilwRblmWl5+6B1LliqsrsizAagXnUOJVh5G0e+32qnrVHnL41mJBS9z4/elYzkJzNZDDUf2Cg/fV9hSv2jYhuHJx3JNN5Mcw2Ku+FswL0dCVQjmdSh3mtV7uAlIiSQL+w==
  template:
    metadata:
      name: sa-platform-authorization-db-secret
      namespace: sa-p8
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sa-platform-jwt-secret
  namespace: sa-p8
spec:
  encryptedData:
    JWT_SECRET: AgBn9swO/NvRYxmPst3YfDlZ+Tzc0UZ+Ij2V0nfFjwKq84d3vXd6GzTJ64Hou5wu/pdL1Ph6Rsf+efHy7Rchlo16rYO9Zb+R5bYQb8EUQzCRQkAulKiCtRpa3RJa29Nn937jtqjZP/O8QjjXZcg7SRiteD3KW1nSOW2E+pGB0rTFsz4Al9rKiftlZPqSGj0QJn4YNViczHBBAhu6kZ2n9nFeMq3lVFe3h2TtEDDzc824nEIkEmBeAO+iJyuMQ8R4e7YheseRm2XMac7OcAHgF/oX3A6sjJ5/NCedpE1ZtxjKriUnI2WcfeNVJB3NZNJZJNlqgkU0y5Inri1c+yCokEmH8C4SjKYRnf0FjI89UZtxmKMmyWCoAWrtGVfQHCaek99AscR+1/DuOAAgXoG5PiDDU4TjPVhLUlaCy7ETip0v9uLhqAvhMlR+/5GB/ZUBlZcJVzzdES8ukJitfUyfifvrUBuEnLJEuItLdX1zcgaY4bnZjWASdvfzQ0aPFuxA6VnIBBvlz4ZFE695yjICjeEM3x+f7idrvE5jcKm2LA8mg5w6saTztVrWnZNy0UzpvGvu4U/WlpfBDdz2ztdvo1heBBHi4KMyXbgCFoc60Aq0GE4y+NsFkhdZtVaV76s2k4xIWgiAQZap3eAkf2ZTA/cdthtlbukq9l/BtIfxeSTogA25i/InrvM3ZVqaAsmLQw8M5ytaV2VyRdvF2VvZe78Z2HD+U62c/mFzdeUvFfQGQ8aCCq23vWnpBiir3xTg8B0yBccyDBoP2XMbwrSltWCT
  template:
    metadata:
      name: sa-platform-jwt-secret
      namespace: sa-p8
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sa-platform-kafka-secret
  namespace: sa-p8
spec:
  encryptedData:
    KAFKA_PASSWORD: AgARnltqsGM+Q1ZisfWmR4NlKvfVdv7kaGezckLcyLXiihQGXbiH/4Eeq7zwlJ2vAo3BVFwAzq3ymrikqH0q9nTIOTlrCZAKIIgHpCxumwhTYBskz584qhMP+foavc/u/PE8X3CvfWbyNk8GAZWE2VPZLGYCVmJll5BNL4lvojp9c1gShWgfNFTUJx5qiPSIa+0vmnoltGK2x0DmETroFvv5u3S+EVtJ2udNdmFl8rM+Kkc/yVVNYQwxGoH3FmgFE8UztjOa4ZxC/lNZp33tHH+G+FSeF9Fjn+tiO8/RuvEw8wGjwlIMKN5HIhYAYoGvSU8+8UtbhOrn/kNa6sx4pXNuWXEKDRsy/MKtERDxjFTvc2pUg3EccwPIpeavGT7kYJ4qpP6BK21YXdvsYDOglCIltDGTvDcja3BL4GDN6MVVSnRwPgNzDx14STrlGXyahb7yVswYdHVenvWwKLw7852zWKflr4ybEltHvbAuCjmaNXV9slHUW52YJ4aYPZ64kxjaz2U/1B9B6W1gH1jSB1Z8ZHAjROmE1ja2InbRdjy4/BHmuW0a8CApTL/F7xU2t/9AS0F8gsskcAu1muE/IxAWodYiWsaB/mGVUqHC7TR0cnCsxbSfVDX4yS7IYbUFyNOUrCNygW+/FUGA+zLahR4ckRiCBcjIP9GJJeHsPvsae+nNh6oA8BWRfAqVAvQDRDfsh3xr0iUJZVCqia+z0UugA/5DbDGI0QD1AMpy+BOHEvXmwouPE9kQrrApNKW8lq8=
    KAFKA_USERNAME: AgB0hnCj+MVHtZ4xHl+iNgPZ+2L+KAgycAGbenlx8qHVcKRfmVXLxB8lKwed7BU+GSPoOJI2FJhFcySGd6DFHwreXEXyEI/snJythF5CBvWs1GzQ5OvtjGR2iAkT1BVfNTfBcE2zstVuf0yUX+6C17fjuArp6/veS0tJ/csSDw5bK1SdwE+grLTobz5KCA+qUVVBbI4hR/ztuHB4G2zPyh6QK8Iva7MIzy7Fsc+OFTVymF9J4SePjJ64b61WDN/1XWNykjAGU1Mh+R4sWKAc0ir2pa7SQgpgOOispeyD0xnFbLGWGu+A1eQho1bEWFJ/6SmhKGIAvAcZJU8ftBm6uEct+9YH/x8A0pB45JNLfySbl5X7n/KFZ6JOzgeldMLZkuI44UEATdtxcEZ8f1Av+WvPfjJWsgBbBdHNC56i0Yly8wuknqN6W35EnTDqhqti8060ko+OPkcvf9cRBwWMV6rnCVKgOJ1hKhr4RVbH++PANQQGTJvlGjd6kvqWD0JYuov9OyHB+99pleh1C84DPMgx4vlUA+JmlwcQaKlaBa4WTzDe1wZvnXYdmEOeS+nEqqvsbJtluRBU796aW6dDw+4o0nGVltmuX2wwHlKnxg3dvCBnEYOLkHwQRiFJurMfvoMdq4hFKeiSbtZ1o2mNvBAol5NzfdB1QNv1MyQI0Qc/D1HChkq3o/EtiLwzkWuOdP+mmzEljthkk133gfXN
    client.properties: AgBcNuLmMI/xi2SLq4+zIa5KbG/PUpcBs7CRQU92zQOhe0UEPk+hzFzcENvCBfZCbVuTbhHA/Kx4XzM7cJYOd9z/PMtzjSNFc/SFFyERhPzmqCDgbTLv3FYDrRPWU+mkDf7XuoaPyldYuhpErlj5+2iJ40Rbwzo7+fmAjy2ImJryazo9DyXuGbU89gs8RlzdwCrhru5HmzYcIqFDS6hu72NjggfWk2aL4pf0nxTJZ46TU92YLyx1M8FIozp+v7Q0872ihvmW5BGgADNXXmFwIEInRfVLko19nicK2jepDh3tLrSDZZcgwVpED8erbHQwFPCPxu4jE00qlQMF8BXxgT2NAJGIvyAhViOwuVXMRZtcT7i4HZcsRW02XjgujwXtYF2tFb3r/xUtUwdI6oWH8rV8YBQ0Pnl4/Xx1nyBaokwRvsJvDJYnvqYZcLtYz8JoQMLcYQqsI7D1YZQxMFPtvbb2DjZbnRPhY8omUImRK7ieBE1G60pAd9GOZLj2RssrSqqLter+P3NRtie23o8ItvDbOzNotJywSvdUQ2U2mgP2buZ23O4w8PMj5jmqOyo7Lzn7lHXFOTMnw1OCymI0/PTtSYSEvhPDCyt3UqTS1CgqOCi3k+4wDcEuiLibMKkuyOC5+P07pBI0BQ1j94pn+CRgWz1ue79HzfkwgM2czDXCQkaNEzY52Yh6/fFOIuflfCl5azQGH1hykZNC8JA4I0JNQmL1uVLK9mDZ8qiz6rAxOFMPAIe5+Zdw/C3T45H/7MAT0I1kAXqqxwxgTSClqfndA+PJy5orrxlyXI0V21tQvxeel5E0CJbr4rf6IFZ09Nls1zMsppurWNjoYKV2TIMQ3LWtP2SdlynVglo8JGnKXoqy9xeYvbTW9SX7o3pJLHKLH6yZ3fZ9A+xQY6a2yk7wt7wR6EWj+UuqofZBTCMc4ztkJWk5HwAmi5kE5T5ytLdwoz9TF/MvmNV8B4GSbZA3+oCScKJT5F4dperspho=
    kafka_server_jaas.conf: AgAIsyIjSH4Yep5lHG+rrp1SQRercll/1gtVQxWQO/0oiI3qGeRmE4uj9TSylZVVe7BIX1b7bba8Til8jgLwkFWGcpVhZdzW3EYb2INbg2XFjSKrXFRY/WvJHeTd+VN3VG2ACzNNwmzuH03qwUcWhGfEvuhXprsu2A7JM+0H6wU5eG2z644uDc0qndJcwAbWJJmw07JzmtV9VA+zUpB+GVjZ+S9JPY5756e3OPqc6v3HLqiYvKKfX4nghiiiEmhIuvUKG3avDHwnctbrMsQDgU4XZUnOJXa4VfU3iaj+p0Bvl+D9RFPAiMckIwlkBmLA5c7CnukB9/JAxaob6jnHcJH7y05Yupoge0JUbdE2dZs/+IryC508778dAdw71TqCnGDrBVDltKtDOB8lnBz6VmhNZDEXnDFF9EKIO6zQkp26tg59rka4/l301MaBnjmNXP7rtxasqS6bCPttUmtSiYM0ZShzZ4F7ip0KY70cF2G/u9ZQyPViSlxltEGj9n2nyct6+h4vRRPk9UTViY0NmvHAkF0/jiy78wfBFpKtelDHi19e8BTz9UfZ+D73YRVVL/eqOVOB/YFzGLBJvQd0JRCvhsdUjfSP6+DkSdRwOy+IN+OPzY5rS4eNmEhaaK8lLY3aSkYo6gjhJ8BXlAM5wfs/AK/FjrbDW1LoPPS2+Lw0/qnkNxymaTAyMwuamvwm49XQ58mLhJ1kS4ziQtWHS+HlA1NQyZFZiCoGijrK8pY5QhQyTYhGYPI0s5PTgiKFDRMWRJQIzSyewzPkK/7cz0rmzAPRFvHKAVkR11z+07JKqepxeZwo0itNlNgT+F3rUaDe100NA5ukDNqCaHgtTY6qAtWDiQSOVWrIqQghUBrZmO8eI3cGe4yblf+AH4V1VX0MDjpXzJsWdT7lvwc9FCkUxehmcZ1dTdfrZms+aVx/2JvhnyS08D9rYt/kQwGlTQlExSqGdbgVC2/WiMxrFGVUYX/3rbo3xkWriE7Fb0Q1dKFyjtFRD7Sp51Aax5ljIlr9o2JvZO8=
  template:
    metadata:
      name: sa-platform-kafka-secret
      namespace: sa-p8
