apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sa-platform-postgresql-admin
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: sa-platform-postgresql-admin
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        POSTGRES_USER: {{ `"{{ .username }}"` }}
        POSTGRES_PASSWORD: {{ `"{{ .password }}"` }}
        PGDATA: /var/lib/postgresql/data/pgdata
  data:
    - secretKey: username
      remoteRef: {key: p9-postgres-user}
    - secretKey: password
      remoteRef: {key: p9-postgres-password}
---
{{- $databases := dict "product" "products_db" "order" "orders_db" "customer" "customers_db" "payment" "payments_db" "authentication" "authentication_db" "authorization" "authorization_db" }}
{{- range $service, $database := $databases }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sa-platform-{{ $service }}-db-secret
  namespace: {{ $.Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: sa-platform-{{ $service }}-db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: {{ printf `"postgresql://{{ .username }}:{{ .password }}@sa-platform-postgresql.sa-p8.svc.cluster.local:5432/%s"` $database }}
  data:
    - secretKey: username
      remoteRef: {key: p9-postgres-user}
    - secretKey: password
      remoteRef: {key: p9-postgres-password}
---
{{- end }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sa-platform-jwt-secret
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: sa-platform-jwt-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        JWT_SECRET: {{ `"{{ .jwt }}"` }}
  data:
    - secretKey: jwt
      remoteRef: {key: p9-jwt-secret}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sa-platform-kafka-secret
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: sa-platform-kafka-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        KAFKA_USERNAME: {{ `"{{ .username }}"` }}
        KAFKA_PASSWORD: {{ `"{{ .password }}"` }}
        client.properties: |
          security.protocol=SASL_PLAINTEXT
          sasl.mechanism=PLAIN
          sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="{{ `{{ .username }}` }}" password="{{ `{{ .password }}` }}";
        kafka_server_jaas.conf: |
          KafkaServer {
            org.apache.kafka.common.security.plain.PlainLoginModule required
            username="{{ `{{ .username }}` }}"
            password="{{ `{{ .password }}` }}"
            user_{{ `{{ .username }}` }}="{{ `{{ .password }}` }}";
          };
  data:
    - secretKey: username
      remoteRef: {key: p9-kafka-username}
    - secretKey: password
      remoteRef: {key: p9-kafka-password}
