apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-platform-runtime
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sa-platform-read-config
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: [configmaps]
    verbs: [get, list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-platform-read-config
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: sa-platform-runtime
    namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sa-platform-read-config
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: sa-p9-quota
  namespace: {{ .Values.namespace }}
spec:
  hard:
    requests.cpu: "6"
    requests.memory: 12Gi
    limits.cpu: "12"
    limits.memory: 24Gi
    pods: "100"
    persistentvolumeclaims: "10"
    requests.storage: 50Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: sa-p9-default-limits
  namespace: {{ .Values.namespace }}
spec:
  limits:
    - type: Container
      default: {cpu: 500m, memory: 512Mi}
      defaultRequest: {cpu: 25m, memory: 64Mi}
